name: Automated build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: 17

      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: AxolotlClient-1.8.9-automation
          path: build/libs/*.jar

