name: Automated build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: AxolotlClient-1.8.9-automation
          path: build/libs/*.jar
  upload:
    if: "startsWith(github.event.head_commit.message, '[create release] ')"
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: p2rxzX0q 
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: subset
          modrinth-featured: true
          
          github-token: ${{ secrets.GH_TOKEN }}
          github-generate-changelog: true
          github-draft: true
