name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: gradle/actions/wrapper-validation@v4

      - uses: actions/setup-java@v4
        if: "github.ref == 'refs/tags/${{ steps.get-latest-tag.outputs.tag }}'"
        with:
          distribution: "temurin"
          java-version: 21

      - name: Build with Gradle
        uses: gradle/actions/gradle-build@v4
        with:
          arguments: build
          cache-read-only: true

      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
          changelog-file: "CHANGELOG.md"
          files: 1.*/build/libs/*
